sudo: required
language: node_js
node_js:
- '0.12'
cache:
  directories:
  - "~/.meteor"
  - node_modules
  - webapp/node_modules
install:
- curl https://install.meteor.com | /bin/sh
- meteor update
script:
- meteor --test --release velocity:METEOR@1.1.0.3_1
deploy:
  provider: heroku
  buildpack: https://github.com/jordansissel/heroku-buildpack-meteor.git
  app: leaderboard-dinf
  api_key:
    secure: W8PVeCRmFRqKKpI8+CjIkB9crpAFwSdcORrwUJ9DNuUTkVmXlIJkHpREgXhDdcG4qM5M0gwSFTkHZGbV1wE7+x9AtuG/w/gazxZEif/GBF8ZnK8h00f3JsxX3EwslSifwn1qfevWGIRIDajOGiSyIvCWyjPaOv/Va1Ny+SmAZzJDJ9tEpF3NKjDsWDGtQQ5jEb9myTgJoQ6Ew24quT/+teDU++0w1+qf+9Z5G5QC8yb6hIScKzqu8QdTXvj8FmQHaPVRdfkaUUhp8eg2rA2dVZ6Dw1Kx5q7FpCVsWgYQoIEciKEv45lKYinHmVH++UFGDgnPE9lGO12SUpQSnZCL6wVr2DgNVtvbiLbzflCZHvqInVcppRA65V6kVsvY45oQtg1eM5sVCTz6RWiE4G5aXbTIbJ7Baun+mObE7azF+UfJt45Dtf6S69ZlgxohlXyS63WHVvOGm+Rt3lMX620yNH+04cONekAQmWZmv77QlwxDrZ485Rh3YMNt0BuO3PRwIsrVVSEG+EAvgoM5JS0UbQM4RRWfhVltblq4CCzu0OZL2yz+aoFRkjlY9CNYejhAxouD62KO0pEs9TMp8Cs3CNUHK+gq/C+0M/xZ3rWmAMPkP2yQxEF0xu7uCZEtdxNaaJ74dUIN4ULiMrfEau+6rJZdX8KfSopPtHUW0V1FFI8=
  on:
    all_branches: true
